### ISSUE TITLE
Standalone

### ISSUE THREAD

**Issue by iamdriz** [skandasoft/browser-plus#37]
Could this be used standalone? As I'm looking to build a really simple web browser for another project in Electron (atom-shell).

**Comment by skandasoft** [comment]
May be you can use the code especially the node integration. But right now this is tied to atom

**Comment by iamdriz** [comment]
The thing I'm struggling with is linking the web view url to an input box for the address bar that's always in sync. As well as back and forward buttons that are linked to the history. Could you point me to where the code is for these? Much appreciated. Thanks

**Comment by skandasoft** [comment]
sorry for the delay response. All the major code is there is https://github.com/skandasoft/browser-plus/blob/master/lib/browser-plus-view.coffee. for the history I am using the riotjs for filter and online update..in https://github.com/skandasoft/browser-plus/blob/master/resources/history.tag ..since node integeration is security issue I have used https://github.com/skandasoft/browser-plus/blob/master/resources/bp-client.js. let me know if you wanted anything.

**Comment by iamdriz** [comment]
Well so far I have this:

// load the url typed into the address bar into the webview
$('#URL').keypress(function(e){
	if(e.which == 13) {
		var $url = $('#URL').val();
		if ( $url.substr(0,7) !== 'http://'
		&& $url.substr(0,8) !== 'https://'
		&& $url.substr(0, 7) !== 'file://' ) {
			$url = 'http://'+$url;
		}
		$('#URL').val($url);
		$('webview').attr('src', $url );
	}
});

The things I don't know how to do are:

- When user clicks a link in the webview and changes the page, update the address bar to match the new url and update the back and forward buttons to be enabled or disabled.
- Store history and navigate through it using the said back and forward buttons.
