### ISSUE TITLE
url bar - only partly vissible

### ISSUE THREAD

**Issue by Tset-Noitamotua** [skandasoft/browser-plus#96]
When I open browser tab the url bar is only partly vissible and thus hard to use:

![image](https://cloud.githubusercontent.com/assets/5635462/17020252/da017000-4f40-11e6-9800-ded3c415851d.png)

System:
Windows 7 64 bit
Atom 1.8.0

**Comment by hirotamz** [comment]
I got this bug too.

OS X 10.11.6
Atom 1.8.0
browser-plus 0.0.67

**Comment by skandasoft** [comment]
I don't have the os. Can you open the developer tool for atom and check what css need to be applied to extend. Currently it is 2 part the one on left of the url input is float left and then one to right is just a block div occuping the entire space. which I think it does. But I put the url overflow to be hidden. can you please around it and send the css patch that can be applied. Appreciate your help.

**Comment by Tset-Noitamotua** [comment]
@skandasoft  feel free to assign it to me, I´ll give it a try

**Comment by skandasoft** [comment]
Please make a PR

**Comment by hirotamz** [comment]
I already reinstall Atom(1.8) & browser-plus(0.074) on OS X 10.11.6
and, I finished add patch(#94 jennuine’s)

But I can’t input url, because the input area is covered by the autocomplete’s view.
Autocomplete not working in my browser-plus???

I checked my problem on developer tool.
I got same error in console.

It’s autocomplete’s bug??? or my mistake???


1) error message in console.
=======================================================================
Uncaught (in promise) DOMException: Failed to execute 'put' on 'IDBObjectStore': An object could not be cloned.(…)dbPromise.then.db @ /Users/hiroyuki/Downloads/Atom.app/Contents/Resources/app.asar/src/state-store.js:33
/Users/hiroyuki/Downloads/Atom.app/Contents/Resources/app.asar/src/state-store.js:33 Uncaught (in promise) DOMException: Failed to execute 'put' on 'IDBObjectStore': An object could not be cloned.(…)dbPromise.then.db @ /Users/hiroyuki/Downloads/Atom.app/Contents/Resources/app.asar/src/state-store.js:33
=======================================================================


2) #94 jennuine’s patch
------------------------------------------------------------------------------------------------
cd ~/.atom/packages/browser-plus
npm install jquery-autocomplete --save

 .atom/packages/browser-plus/lib/browser-plus-view.coffee, update 
#jQACPath = "#{atom.packages.getPackageDirPaths()[0]}/browser-plus/node_modules/jquery-ui/autocomplete.js"
jQACPath = "#{atom.packages.getPackageDirPaths()[0]}/browser-plus/node_modules/jquery-autocomplete/jquery.autocomplete.js"

atom/packages/browser-plus/node_modules/jquery-autocomplete/jquery.autocomplete.js,
add jQuery = require('../jquery/dist/jquery.js'); 
-----------------------------------------------------------------------------------------------



I just want to write url on url-bar, so I modified css for I kill autocomplete.
xdsoft_autocomplete_hint with:1px

Autocomplete not working, but now I can write to the url-bar. 
I'm very happy now. 

Browser-plus is good plugin, I love it.
thanks.

**Comment by skandasoft** [comment]
probably I am going to make autocomplete optional..lot of folks are having issues with it.

**Comment by skandasoft** [comment]
Check the latest patch/FAQ
